#!/bin/sh
# WordPress Plugin pre-commit hook

set -e

# PHPUnit
if [ -e phpunit.xml ] || [ -e phpunit.xml.dist ]; then
	# @todo Check if WP_TESTS_DIR is not set
	if [ command -v phpunit >/dev/null 2>&1 ]; then
		phpunit
	else:
		echo "Skipping phpunit since not installed"
	fi
fi

# JSHint
if [ -e .jshintrc ]; then
	if command -v jshint >/dev/null 2>&1; then
		jshint .
	else
		echo "Skipping jshint since not installed"
	fi
fi

# PHP_CodeSniffer WordPress Coding Standards
changed_php_files=$(git status --porcelain | egrep '^.[MARC]' | cut -c4- | egrep '.php$' | wc -l)
if [ $changed_php_files != 0 ]; then
	if command -v jshint >/dev/null 2>&1; then
		phpcs_standard=$(if [ -e ruleset.xml ]; then echo ruleset.xml; else echo WordPress; fi)
		phpcs -p -s -v --standard=$phpcs_standard $(git status --porcelain | egrep '^.[MARC]' | cut -c4- | egrep '.php$')
	else
		echo "Skipping phpcs since not installed"
	fi
fi

# Make sure the readme.md never gets out of sync with the readme.txt
generate_markdown_readme=$(find . -name generate-markdown-readme -print -quit)
if [ -n "$generate_markdown_readme" ]; then
	markdown_readme_path=$($generate_markdown_readme)
	git add $markdown_readme_path
fi