#!/bin/bash
# WordPress Plugin pre-commit hook

set -e

# via http://unix.stackexchange.com/a/13474
upsearch () {
	slashes=${PWD//[^\/]/}
	directory="./"
	for (( n=${#slashes}; n>0; --n )); do
		test -e "$directory/$1" && echo "$directory/$1" && return
		directory="$directory/.."
	done
}

WP_TESTS_DIR=/tmp/wordpress-tests/

YUI_COMPRESSOR_CHECK=1
DISALLOW_EXECUTE_BIT=0
PARENT_DIR_SLUG=$(basename $(dirname $(pwd)))
SELF_DIR=$( pwd )
PHPCS_DIR=/tmp/phpcs
PHPCS_GITHUB_SRC=squizlabs/PHP_CodeSniffer
PHPCS_GIT_TREE=master
PHPCS_IGNORE='tests/*,vendor/*'
WPCS_DIR=/tmp/wpcs
WPCS_GITHUB_SRC=WordPress-Coding-Standards/WordPress-Coding-Standards
WPCS_GIT_TREE=master
PHPCS_FILE=$( upsearch phpcs.ruleset.xml )
WPCS_STANDARD=$(if [ ! -z "$PHPCS_FILE" ]; then echo "$PHPCS_FILE"; else echo WordPress-Core; fi)
ENV_FILE=$( upsearch .ci-env.sh )
if [ ! -z "$ENV_FILE" ]; then
	source "$ENV_FILE"
fi

MESSAGE="Checking staged changes..."
GIT_STATUS_EGREP='^[MARC].+'

for i; do
	case "$i"
	in
		-m)
			MESSAGE="Checking any uncommitted changes..."
			GIT_STATUS_EGREP='^.?[MARC].+'
			shift;;
	esac
done

echo "$MESSAGE"

# Check for staged JS files
IFS=$'\n' STAGED_JS_FILES=( $(git status --porcelain | sed 's/[^ ]* -> *//g' | egrep $GIT_STATUS_EGREP'\.js$' | cut -c4-) )
if [ ${#STAGED_JS_FILES[@]} != 0 ]; then
	# YUI Compressor
	if [ "$YUI_COMPRESSOR_CHECK" == 1 ] && command -v java >/dev/null 2>&1; then
		YUI_COMPRESSOR_PATH=/tmp/yuicompressor-2.4.8.jar
		if [ ! -e "$YUI_COMPRESSOR_PATH" ]; then
			wget -O "$YUI_COMPRESSOR_PATH" https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
		fi
		java -jar "$YUI_COMPRESSOR_PATH" -o /dev/null "${STAGED_JS_FILES[@]}" 2>&1
	fi

	# JSHint
	echo "## jslint"
	if command -v jshint >/dev/null 2>&1; then
		jshint "${STAGED_JS_FILES[@]}"
	else
		echo "Skipping jshint since not installed"
	fi

fi

# Check for staged PHP files
IFS=$'\n' STAGED_PHP_FILES=( $(git status --porcelain | sed 's/[^ ]* -> *//g' | egrep $GIT_STATUS_EGREP'\.php$' | cut -c4-) )
if [ ${#STAGED_PHP_FILES[@]} != 0 ]; then
	# PHP Syntax Check
	for PHP_FILE in "${STAGED_PHP_FILES[@]}"; do
		php -lf $PHP_FILE
	done

	# PHPUnit
	PHPUNIT_XML_FILE=$( upsearch phpunit.xml )
	if [ -z "$PHPUNIT_XML_FILE" ]; then
		PHPUNIT_XML_FILE=$( upsearch phpunit.xml.dist )
	fi
	if [ ! -z "$PHPUNIT_XML_FILE" ]; then
		echo "## phpunit"
		if [ "$USER" != 'vagrant' ]; then

			# Check if we're in VVV
			VAGRANTFILE=$( upsearch Vagrantfile )
			if [ ! -z "$VAGRANTFILE" ] && grep -q vvv "$VAGRANTFILE"; then
				cd $( dirname "$VAGRANTFILE" )
				VVV_ROOT=$(pwd)
				ABSOLUTE_VVV_PATH=/srv${SELF_DIR:${#VVV_ROOT}}
				cd "$SELF_DIR"
			fi

			if [ ! -z "$ABSOLUTE_VVV_PATH" ]; then
				echo "Running phpunit in VVV"
				vagrant ssh -c "cd $ABSOLUTE_VVV_PATH && phpunit -c $PHPUNIT_XML_FILE"
			elif command -v vassh >/dev/null 2>&1; then
				echo "Running phpunit in vagrant via vassh..."
				vassh phpunit -c "$PHPUNIT_XML_FILE"
			fi
		elif ! command -v phpunit >/dev/null 2>&1;then
			echo "Skipping phpunit since not installed"
		elif [ -z "$WP_TESTS_DIR" ]; then
			echo "Skipping phpunit since WP_TESTS_DIR env missing"
		else
			phpunit -c "$PHPUNIT_XML_FILE"
		fi
	fi

	# PHP_CodeSniffer WordPress Coding Standards
	echo "## phpcs"
	if command -v phpcs >/dev/null 2>&1; then
		phpcs -p -s -v --standard="$WPCS_STANDARD" $(if [ -n "$PHPCS_IGNORE" ]; then echo --ignore="$PHPCS_IGNORE"; fi) "${STAGED_PHP_FILES[@]}"
	else
		echo "Skipping phpcs since not installed"
	fi
fi

# Check for staged files with execute bit on
if [ "$DISALLOW_EXECUTE_BIT" == 1 ]; then
	for EXECUTABLE_FILE in $( find . -perm -g=x -type f ); do
		if [ "" != $( git status --porcelain "$EXECUTABLE_FILE" | sed 's/[^ ]* -> *//g' | egrep "$GIT_STATUS_EGREP" | cut -c4- ) ]; then
			echo "Error: Executable file being committed: $EXECUTABLE_FILE. Do chmod -x on this."
			exit 1
		fi
	done
fi

# Make sure the readme.md never gets out of sync with the readme.txt
if [ -e readme.txt ]; then
	# TODO: This is not going to work if wp-plugin-dev-lib is outside of the repo
	GENERATE_MARKDOWN_README=$(find . -name generate-markdown-readme -print -quit)
	if [ -n "$GENERATE_MARKDOWN_README" ]; then
		MARKDOWN_README_PATH=$($GENERATE_MARKDOWN_README)
		git add $MARKDOWN_README_PATH
	fi
fi
