#!/bin/bash
# WordPress prepare-commit-msg hook

DEV_LIB_COMMIT_MESSAGE_FILE=".dev-lib-commit-message.$PPID"

if [ -f "$DEV_LIB_COMMIT_MESSAGE_FILE" ]; then
	COMMIT_EDITMSG=$1
	cat "$DEV_LIB_COMMIT_MESSAGE_FILE" >> $COMMIT_EDITMSG
	unlink "$DEV_LIB_COMMIT_MESSAGE_FILE"
fi

