#!/bin/bash
# WordPress prepare-commit-msg hook

COMMIT_EDITMSG=$1

JIRA_TASK_REGEXP='.*([A-Z]{1,32}-[0-9]{1,32}).*'
JIRA_BRANCH_REGEXP='([a-zA-Z]+-[0-9]{1,32})';
if [[ ! $(cat "$COMMIT_EDITMSG") =~ $JIRA_TASK_REGEXP ]]; then
	JIRA_TASK=$(git rev-parse --abbrev-ref HEAD | grep -oP "$JIRA_BRANCH_REGEXP")
	if [ -n "$JIRA_TASK" ]; then
		MESSAGE=`cat $COMMIT_EDITMSG`
		echo "${JIRA_TASK^^}: $MESSAGE" > $COMMIT_EDITMSG
	fi
fi
